name: Build and push Docker image

on:
  push:
    branches-ignore:
      - "dependabot/**/*"
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: ghcr.io/zazuko/cube-link

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Replace draft status
        run: sed -i 's/"ZZ-DRAFT"/"ZZ-BASIC"/g' config.js meta/config.js relation/config.js

      - name: Remove 'issue-summary' section
        run: sed -i '/issue-summary/d' index.html meta/index.html relation/index.html

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.DOCKER_IMAGE }}"
          tags: |
            type=ref,event=branch
            type=semver,prefix=v,pattern={{version}}
            type=semver,prefix=v,pattern={{major}}.{{minor}}
            type=semver,prefix=v,pattern={{major}}
            type=sha

      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' || !contains(github.ref, 'dependabot') }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
